epochs: 20000
eval_interval: 2000
global_batch_size: 384
lr: 0.0001
lr_min_ratio: 0.1
lr_warmup_steps: 2000
puzzle_emb_lr: 0.0001
weight_decay: 1.0
puzzle_emb_weight_decay: 1.0
beta1: 0.9
beta2: 0.95
optimizer: "AdamW"
optimizer_eps: 1.0e-8
seed: 0
checkpoint_every_eval: false
eval_save_outputs: []
smoke_test: false
num_workers: 1
prefetch_factor: 8
lr_schedule: "cosine"
use_amp: false
